### ISSUE TITLE
Translation expression

### ISSUE THREAD

**Issue by saldroubi** [mdowst/PSDates#1]
Hello,

I would like a function that I pass a cron expression and it would translate it to English.  Is this available?  
Something similar to what is available on this website:  https://bradymholt.github.io/cron-expression-descriptor/
but a PowerShell function 

Thank you.

**Comment by mdowst** [comment]
The functionality has been added in version 1.0.1.

https://www.powershellgallery.com/packages/PSDates/1.0.1
